title: "영케터의 마케팅 블로그"
tagline: "디지털마케팅"
description: "영케터가 구글, SNS, 디지털 마케팅을 도와드립니다."
permalink: ':title/'
baseurl: "/"
url: "https://youngketer.com"
locale: "ko_KR"
thumbnail: "/img/youngketer_thumbnail.jpg"
copyright: youngketer.com

# Author Settings
author: <h1>"디지털마케터<br>영케터"</h1>
author-img: /img/profile.png # add your photo
about-author: "언제 어디서나 고민하는 영케터에게 문의가 있다면 하단 CONTACT ME를 눌러주세요!" # add description
social-instagram: youngketer_cho
social-facebook: choyoungketer
social-email: wwjocom88@gmail.com

# 블로그 disqus shortname
disqus:
  shortname: everythegame-com


# Build Settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
