title: "영케터의 마케팅 블로그"
tagline: "디지털마케팅"
description: "구글,SNS광고 등 디지털 마케팅을 알고 싶다면 영케터로 오세요"
permalink: ':title/'
baseurl: "/"
url: "https://youngketer.com"
locale: "ko_KR"
thumbnail: "/img/everythegame_thumbnail.jpg"
copyright: youngketer.com

# Author Settings
author: "영케터"
author-img: /img/profile.png # add your photo
about-author: "구글, SNS등 다양한 광고가 궁금하다면 주저하지 말고 들어오세요!" # add description
social-instagram: sleeping__cho
social-facebook: everythegame
social-email: wwjocom88@gmail.com

# 블로그 disqus shortname
disqus:
  shortname: everythegame-com


# Build Settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
